#!/bin/bash

# This script will encrypt all unencrypted snapshots in an AWS account. You can uncommet the Delete unencrypted snapshot line if you'd like, but it will not delete snapshots attached to AMI's.

echo
echo "Let's begin!"

# Get unencrypted snapshot Id's
snaps=$(aws ec2 describe-snapshots --region us-east-1 --filters Name=owner-id,Values=940078136635  | grep -A 7 false | grep SnapshotId | sed 's/"\|:\|SnapshotId\| //g')

# Loop through the unecnrypted snapshots

count=1
for j in $snaps; do


# Retrieve the tag
tag=$(aws ec2 describe-snapshots --region us-east-1 --snapshot-id $j --filter Name=tag-key,Values=Name | grep Value | sed 's/"\|:\|,\|Value\| //g')
descr=$(aws ec2 describe-snapshots --region us-east-1 --snapshot-id $j --filter Name=description,Values=* | grep Description | sed -e 's/"\|:\|,\|Description//g' -e 's/^[ \t]*//')

echo ________________________________
echo Snapshot \#$count
echo
echo Copying Snapshot $j

# Copy the snapshots
snapcopy=$(aws ec2 copy-snapshot --source-region us-east-1 --source-snapshot-id $j --encrypted --description "$descr"  | sed 's/{\|}\|"\|:\|SnapshotId\| //g')

echo
echo Waiting for the snapshot to create

# Wait for the snapshot
aws ec2 wait snapshot-completed --snapshot-ids $snapcopy

echo Transfering tags and description
# Tag it with original Name tag
aws ec2 create-tags --region us-east-1 --resources $snapcopy --tags Key=Name,Value=$tag

# Delete the unencrypted snapshot
#aws ec2 delete-snapshot --snapshot-id $j --region us-east-1

echo Getting next snapshot
echo
(( count++ ))
done

Success! We encrypted $count snapshots.
